theme = "default"
client_id = "326a442f2ab041b694df38b5eabffba5"
client_port = 8080
playback_format = """
{track} • {artists}
     from: {album}

  {metadata}"""
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "  ▶"
pause_icon = "  ⏸"
liked_icon = "♥"
border_type = "Rounded"
progress_bar_type = "Line"
playback_window_position = "Top"
cover_img_length = 9
cover_img_width = 4
cover_img_scale = 1.2
playback_window_width = 6
enable_media_control = true
enable_streaming = "Always"
enable_notify = false
enable_cover_image_cache = true
default_device = "Arch"
notify_streaming_only = true

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[device]
name = "Arch"
device_type = "computer"
volume = 80
bitrate = 320
audio_cache = false
normalization = false
